Avoid errors when '%' in bot name
To avoid errors for % in botname, it will be changed to %%

Traceback (most recent call last):
  File "/home/M1cha3l/3commas-cyber-bots/galaxyscore.py", line 320, in <module>
    config = upgrade_config(logger, api, config)
  File "/home/M1cha3l/3commas-cyber-bots/galaxyscore.py", line 94, in upgrade_config
    cfg[f"bot_{thebot}"] = {
  File "/usr/local/lib/python3.9/configparser.py", line 974, in __setitem__
    self.read_dict({key: value})
  File "/usr/local/lib/python3.9/configparser.py", line 754, in read_dict
    self.set(section, key, value)
  File "/usr/local/lib/python3.9/configparser.py", line 1201, in set
    super().set(section, option, value)
  File "/usr/local/lib/python3.9/configparser.py", line 894, in set
    value = self._interpolation.before_set(self, section, option,
  File "/usr/local/lib/python3.9/configparser.py", line 402, in before_set
    raise ValueError("invalid interpolation syntax in %r at "
ValueError: invalid interpolation syntax in '100eyes 2489USDT 10MAD max60% - All 1h/4h/1d - Galaxy50' at position 28